# Random Forest Regressor Configuration

# Data parameters
ticker: "BTC-USD"
start_date: "2016-05-22"
end_date: "2024-07-24"
test_size: 0.2

# Directories
model_dir: "models"
plot_dir: "plots"

# Hyperparameter tuning
hyperparameter_tuning:
  n_estimators:
    - 100
    - 200
    - 300
    - 400
    - 500
  max_features:
    - "auto"
    - "sqrt"
  max_depth:
    - 10
    - 20
    - 30
    - 40
    - 50
    - 60
    - 70
    - 80
    - 90
    - 100
    - null
  min_samples_split:
    - 2
    - 5
    - 10
  min_samples_leaf:
    - 1
    - 2
    - 4
  bootstrap:
    - true
    - false